import { withModalTheme } from '@mattjennings/react-modal';
import { Theme } from 'theme-ui';

const theme = (function () {
  const customTheme = {
    breakpoints: ['32em', '48em', '64em', '96em', '128em'],
    space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
    fonts: {
      body: '"DM Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
      heading:
        '"DM Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
      monospace:
        '"DM Sans", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    },
    fontSizes: [12, 16, 20, 28, 32, 40, 48, 60],
    fontWeights: {
      body: 400,
      heading: 700,
      bold: 700,
      medium: 500,
      regular: 400,
    },
    lineHeights: {
      body: 1.5,
      heading: 1.25,
    },
    text: {
      default: {
        fontFamily: 'body',
        fontWeight: 'body',
        fontSize: 1,
        lineHeight: 'body',
      },
      caps: {
        fontFamily: 'body',
        fontWeight: 'body',
        fontSize: 0,
        lineHeight: 'body',
        textTransform: 'uppercase',
      },
      heading: {
        fontFamily: 'heading',
        fontWeight: 'heading',
        lineHeight: 'heading',
      },
    },
    links: {
      focus: { textDecoration: 'none', color: 'secondary', border: '1px solid', borderColor: 'secondary', p: 1 },
      visited: { textDecoration: 'underline', color: 'muted' },
      hover: { textDecoration: 'underline', color: 'primary', cursor: 'pointer' },
    },
    colors: {
      text: '#0E0E0E',
      background: '#FFFFFF',
      primary: '#FFDA00',
      // secondary: '#1B202E',
      // accent: '#2B40B5',
      // highlight: '#E4E6EC',
      // muted: '#9AA0B5',
      // gray0: '#9AA0B5',
      // gray1: '#E4E6EC',
      // gray2: '#EEEFF3',
      // gray3: '#F6F6F9',
      // error: '#E03B54',
      // success: '#00CD98',
      blue: {
        '100': '#F2F7FF',
        '200': '#CCDFFF',
        '300': '#99C0FF',
        '400': '#4775EA',
      },
      red: {
        '100': '#FFF0F3',
        '200': '#FF99B9',
        '300': '#E72C43',
        '400': '#B30038',
      },
      orange: {
        '100': '#FFEDDD',
        '200': '#F7A75E',
        '300': '#F18C2F',
        '400': '#D9761B',
      },
      yellow: {
        '100': '#FFFCE0',
        '200': '#FFF9C2',
        '300': '#FFDA00',
        '400': '#DFAF05',
      },
      green: {
        '100': '#E7FFFC',
        '200': '#4FE6C1',
        '300': '#00B388',
        '400': '#005B52',
      },
      dark: {
        '100': '#EBEBEB',
        '200': '#C2C2C2',
        '300': '#5C5C5C',
        '400': '#0E0E0E',
      },
      white: {
        '100': 'rgba(255, 255, 255, 0.1)',
        '200': 'rgba(255, 255, 255, 0.4)',
        '300': 'rgba(255, 255, 255, 0.7)',
        '400': '#FFFFFF',
      },
    },
    radii: {
      none: 0,
      sm: 2,
      base: 4,
      md: 6,
      lg: 8,
      xl: 12,
      '2xl': 16,
      '3xl': 24,
      circle: 9999,
    },
    shadows: {
      xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      base: '0 1px 3px 0 rgba(0, 0, 0, 0.1),0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1),0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1),0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1),0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      outline: '0 0 0 3px rgba(66, 153, 225, 0.6)',
      inner: 'inset 0 2px 4px 0 rgba(0,0,0,0.06)',
      none: 'none',
      'dark-lg': 'rgba(0, 0, 0, 0.1) 0px 0px 0px 1px,rgba(0, 0, 0, 0.2) 0px 5px 10px,rgba(0, 0, 0, 0.4) 0px 15px 40px',
    },
    badges: {
      primary: { backgroundColor: 'gray1', borderRadius: '38px', color: 'text', py: 1, px: 3 },
      success: { backgroundColor: 'success', borderRadius: '38px', color: 'background', py: 1, px: 3 },
      lightest: { backgroundColor: 'gray2', borderRadius: '38px', color: 'gray0', py: 1, px: 3 },
      warning: { backgroundColor: 'primary', borderRadius: '38px', color: 'background', py: 1, px: 3 },
      darker: { backgroundColor: 'secondary', borderRadius: '38px', color: 'background', py: 1, px: 3 },
      error: { backgroundColor: 'error', borderRadius: '38px', color: 'background', py: 1, px: 3 },
    },
    buttons: {
      primary: {
        variant: 'styles.button',
        border: '2px solid transparent',
        backgroundColor: 'yellow.300',
        color: 'dark.400',
        // '&:active': { border: '2px solid #0E0E0E !important' },
        // '&:hover': { border: '2px solid #DFAF05' },
        // '&:focus': { border: '2px solid #DFAF05', bg: '#DFAF05 !important' },
        // '&:disabled,&[disabled]': { cursor: 'not-allowed', bg: 'highlight', color: 'muted' },
      },
      ghost: {
        variant: 'styles.button',
        border: '2px solid transparent',
        backgroundColor: 'transparent',
        color: 'blue.400',
        // transition: 'background-color 0.3s',
        // '&:active': { bg: '#E39256' },
        // '&:disabled,&[disabled]': { cursor: 'not-allowed', bg: 'highlight', color: 'muted' },
      },
      link: {
        py: 0,
        px: 0,
        fontFamily: 'body',
        fontWeight: 'bold',
        fontSize: 2,
        color: 'blue.400',
        backgroundColor: 'transparent',
        boxSizing: 'border-box',
        outline: 'none',
        cursor: 'pointer',
        // transition: 'background-color 0.3s',
        // '&:active': { bg: '#E39256' },
        // '&:disabled,&[disabled]': { cursor: 'not-allowed', bg: 'highlight', color: 'muted' },
      },
      'small-primary': {
        variant: 'buttons.primary',
        px: 16,
        height: 40,
        fontSize: 1,
      },
      'small-ghost': {
        variant: 'buttons.ghost',
        px: 16,
        height: 40,
        fontSize: 1,
      },
      'small-link': {
        variant: 'buttons.link',
        px: 16,
        height: 40,
        fontSize: 1,
      },
      // outline: {
      //   py: '8px',
      //   px: 3,
      //   fontFamily: 'body',
      //   borderRadius: '38px',
      //   outline: 'none',
      //   cursor: 'pointer',
      //   transition: 'background-color 0.3s, box-shadow 0.3s',
      //   bg: 'transparent',
      //   boxShadow: 'inset 0 0 0 3px var(--theme-ui-colors-secondary, #1B202E)',
      //   color: 'text',
      //   '&:active': { bg: 'gray2' },
      //   '&:hover': { boxShadow: 'inset 0 0 0 3px var(--theme-ui-colors-secondary, #FFA665)' },
      //   '&:disabled,&[disabled]': {
      //     cursor: 'not-allowed',
      //     bg: 'highlight',
      //     boxShadow: 'inset 0 0 0 3px var(--theme-ui-colors-muted, #9AA0B5)',
      //     color: 'muted',
      //   },
      // },
      // warning: {
      //   py: '8px',
      //   px: 3,
      //   fontFamily: 'body',
      //   borderRadius: '38px',
      //   outline: 'none',
      //   cursor: 'pointer',
      //   bg: 'transparent',
      //   transition: 'background-color 0.3s, box-shadow 0.3s',
      //   boxShadow: 'inset 0 0 0 3px var(--theme-ui-colors-errors, #E03B54)',
      //   color: 'error',
      //   '&:active': { bg: 'gray2' },
      //   '&:disabled,&[disabled]': {
      //     cursor: 'not-allowed',
      //     bg: 'highlight',
      //     boxShadow: 'inset 0 0 0 3px var(--theme-ui-colors-error, #E03B54)',
      //     color: 'muted',
      //   },
      // },
      // destructive: {
      //   py: '8px',
      //   px: 3,
      //   fontFamily: 'body',
      //   borderRadius: '38px',
      //   outline: 'none',
      //   cursor: 'pointer',
      //   bg: 'error',
      //   color: 'background',
      //   transition: 'background-color 0.3s',
      //   '&:active': { bg: '#CB374D' },
      //   '&:disabled,&[disabled]': { cursor: 'not-allowed', bg: 'highlight', color: 'muted' },
      // },
      icon: {
        height: 56,
        width: 56,
        backgroundColor: 'transparent',
        boxSizing: 'border-box',
        outline: 'none',
        cursor: 'pointer',
        // '&:disabled,&[disabled]': { cursor: 'not-allowed', color: 'muted' }
      },
    },
    // forms: {
    //   checkbox: { 'input:checked ~ &': { color: 'secondary' }, 'input:disabled ~ &': { color: 'gray1', bg: 'gray2' } },
    //   radio: { 'input:checked ~ &': { color: 'secondary' }, 'input:disabled ~ &': { color: 'gray1', bg: 'gray2' } },
    //   select: {
    //     fontFamily: 'body',
    //     borderRadius: '23px',
    //     border: '1px solid',
    //     borderColor: 'gray1',
    //     px: 3,
    //     py: '0.812rem',
    //     '&:focus,&:not(:placeholder-shown)': { outline: 'none', borderColor: 'gray0' },
    //     '::placeholder,:-ms-input-placeholder,::-ms-input-placeholder': { color: 'gray0' },
    //     '&:disabled,&[disabled]': { bg: 'highlight', color: 'muted' },
    //     '& + svg': { ml: '-3.125rem' },
    //   },
    //   input: {
    //     fontFamily: 'body',
    //     borderRadius: '23px',
    //     border: '1px solid',
    //     borderColor: 'gray1',
    //     px: 3,
    //     py: '0.812rem',
    //     '&:focus,&:not(:placeholder-shown)': { outline: 'none', borderColor: 'gray0' },
    //     '::placeholder,:-ms-input-placeholder,::-ms-input-placeholder': { color: 'gray0' },
    //     '&:disabled,&[disabled]': { bg: 'highlight', color: 'muted' },
    //   },
    //   textarea: {
    //     fontFamily: 'body',
    //     borderRadius: '23px',
    //     border: '1px solid',
    //     borderColor: 'gray1',
    //     px: 3,
    //     py: '0.812rem',
    //     '&:focus,&:not(:placeholder-shown)': { outline: 'none', borderColor: 'gray0' },
    //     '::placeholder,:-ms-input-placeholder,::-ms-input-placeholder': { color: 'gray0' },
    //     '&:disabled,&[disabled]': { bg: 'highlight', color: 'muted' },
    //   },
    //   error: {
    //     fontFamily: 'body',
    //     borderRadius: '23px',
    //     border: '1px solid',
    //     borderColor: 'error',
    //     px: 3,
    //     py: '0.812rem',
    //     '&:focus,&:not(:placeholder-shown)': { outline: 'none', borderColor: 'error' },
    //     '::placeholder,:-ms-input-placeholder,::-ms-input-placeholder': { color: 'gray0' },
    //     '&:disabled,&[disabled]': { bg: 'highlight', color: 'muted' },
    //   },
    // },
    styles: {
      root: {
        height: '100%',
        '#root': {
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
          maxWidth: '100%',
          width: '100vw',
          backgroundColor: 'white.400',
        },
      },
      button: {
        py: 0,
        px: 24,
        height: 60,
        minWidth: 48,
        fontFamily: 'body',
        fontWeight: 'bold',
        fontSize: 2,
        borderRadius: 'base',
        boxSizing: 'border-box',
        outline: 'none',
        cursor: 'pointer',
      },
      h1: { variant: 'text.heading', fontSize: '3.75rem' },
      h2: { variant: 'text.heading', fontSize: '3rem' },
      h3: { variant: 'text.heading', fontSize: '2.5rem' },
      h4: { variant: 'text.heading', fontSize: '2rem' },
      h5: { variant: 'text.heading', fontSize: '1.75rem' },
      h6: { variant: 'text.heading', fontSize: '1.25rem' },
      pre: { fontFamily: 'monospace', overflowX: 'auto', code: { color: 'inherit' } },
      code: { fontFamily: 'monospace', fontSize: 'inherit' },
      table: { width: '100%', borderCollapse: 'separate', borderSpacing: 0 },
      th: { textAlign: 'left', borderBottomStyle: 'solid' },
      td: { textAlign: 'left', borderBottomStyle: 'solid' },
      a: {
        color: 'accent',
        textDecoration: 'underline',
        '&:hover': { variant: 'links.hover' },
        '&:focus': { variant: 'links.focus' },
        '&:visited': { variant: 'links.visited' },
      },
    },
  } as Theme;

  return withModalTheme({
    ...customTheme,
    modals: {
      content: {
        flexGrow: 1,
        overflowY: 'auto',
      },
      default: {
        backgroundColor: 'white.400',
        display: 'flex',
        flexDirection: 'column',
        marginY: 'auto',
        maxWidth: 500,
        zIndex: 'modal',
        boxShadow: 'dark-lg',
      },
    },
  });
})();

export type ExactTheme = typeof theme;

export default theme;
